Session 7: JSON
YumNumm/flutter-training pull request #34
Opened 2023-04-11 01:29 UTC by YumNumm

## 課題

close #18

## 対応箇所

## 動作
変更はありません

2023-04-11 01:41 UTC, blendthink commented on analysis_options.yaml
> +    - "**/*.gen.dart"
@YumNumm 
[FYI]
https://twitter.com/_mono/status/1536907414490222593?s=20

2023-04-11 03:30 UTC, YumNumm commented on analysis_options.yaml
> +    - "**/*.gen.dart"
こちらのbuild_runner生成ファイルの頭にignoreをつける方法の方が、
今後様々な生成を行うようになった時に、毎回`analysis_options.yaml`を編集する必要がなく 良いと感じました!
ありがとうございます!

399dc31a41698d74273c7209b83c90c018a8408e

2023-04-11 06:24 UTC, YumNumm commented
@blendthink 本PR、マージしても大丈夫そうでしたら お手すきの際にApproveお願いします!

2023-04-11 09:47 UTC, blendthink requested changes
@YumNumm 
いくつかコメントしましたので、ご確認お願いします！

2023-04-11 09:47 UTC, blendthink commented on lib/features/weather/model/fetch_weather_response.dart
> +  factory FetchWeatherResponse.fromJson(Map<String, dynamic> json) =>
[nits]
フォーマットされていないかも、、？

2023-04-11 09:47 UTC, blendthink commented on lib/features/weather/model/fetch_weather_response.dart
> -    }
[ask]
以前行っていた、これらの処理がなくなったときの挙動確認しましたか？

確認して挙動の認識あっていれば修正不要です 🙆‍♂️

2023-04-11 09:47 UTC, blendthink commented on lib/features/weather/model/fetch_weather_response.dart
> -        WeatherCondition.fromString(json['weather_condition'].toString());
[must]
`fromString()` が使われなくなったようですので削除お願いします！

もし使いたい！という場合には、 `JsonConverter` を独自に用意しなければならなさそうです。

2023-04-12 00:50 UTC, YumNumm commented on lib/features/weather/model/fetch_weather_response.dart
> +  factory FetchWeatherResponse.fromJson(Map<String, dynamic> json) =>
ありがとうございます!
`dart format --fix`を行ったところ修正されませんでしたが、改行すべきだと思うので 手動で修正しました
702bede78da07849d16803bb259a5f540630ebf9

2023-04-12 01:04 UTC, YumNumm commented on lib/features/weather/model/fetch_weather_response.dart
> -    }
確認済みです!
`FetchWeatherResponse`でJSON変換失敗した場合、`WeatherViewmodel`でtry-catchされ`Result.failure()`が返されるようになっています!

![image](https://user-images.githubusercontent.com/73390859/231320589-1e43bd99-aef8-4703-8ad6-44cbf0928659.png)

2023-04-12 01:06 UTC, YumNumm commented on lib/features/weather/model/fetch_weather_response.dart
> -        WeatherCondition.fromString(json['weather_condition'].toString());
ありがとうございます! 
消去しました
084e807

2023-04-12 01:08 UTC, blendthink commented on lib/features/weather/model/fetch_weather_response.dart
> -        WeatherCondition.fromString(json['weather_condition'].toString());
何かいろいろと修正内容おかしいかも、、
ご確認お願いします〜

2023-04-12 01:11 UTC, YumNumm commented on lib/features/weather/model/fetch_weather_response.dart
> -        WeatherCondition.fromString(json['weather_condition'].toString());
コミットへのリンク誤っており、かつ デバッグ用に修正した部分が入っていました。
強制プッシュしましたので 再度確認お願いします!

2023-04-12 01:25 UTC, blendthink commented on lib/features/weather/model/fetch_weather_response.dart
> -    }
@YumNumm 
それはおそらく `jsonDecode` で発生した例外ですよね

[ask]
このようにするとダイアログ表示されないと思いますが、想定通りでしょうか？

```dart
//...
      const jsonResponse = '''
{
    "weather_condition": "sunny-demo",
    "date": "2021-01-01",
    "max_temperature": 10,
    "min_temperature": 0
}''';
      final weatherResponse = FetchWeatherResponse.fromJson(
        jsonDecode(jsonResponse) as Map<String, dynamic>,
      );
//...
```

2023-04-12 04:49 UTC, YumNumm commented on lib/features/weather/model/fetch_weather_response.dart
> -    }
むむむ これは想定していませんでした。
ただ、これらの問題を`json_serializable`を使いつつ対処しようとすると、
```diff
@freezed
class FetchWeatherResponse with _$FetchWeatherResponse {
  factory FetchWeatherResponse({
-    required WeatherCondition weatherCondition,
+    required String? weatherCondition,
-    required DateTime date,
+    required String? date,
    required int maxTemperature,
    required int minTemperature,
  }) = _FetchWeatherResponse;
```
にして、Viewmodelで変換する必要がある気がして、流石にやりすぎなのではないか と思いました。
このままで良いかなと思ったのですがどうでしょうか?

2023-04-12 05:09 UTC, blendthink commented on lib/features/weather/model/fetch_weather_response.dart
> -    }
@YumNumm 
> Viewmodelで変換する必要がある気がして、流石にやりすぎなのではないか と思いました。
既存のままで良いかなと思ったのですがどうでしょうか?

はい、既存のままで問題ありません！
きちんと認識した上での修正かどうかはとても大切ですので、今回コメントさせていただきました！

では確認できましたので Approve させていただきます！

2023-04-12 05:09 UTC, blendthink approved these changes
![LGTM](https://image.lgtmoon.dev/204891)

2023-04-12 05:10 UTC, merged