アーキテクチャの見直し
YumNumm/flutter-training pull request #37
Opened 2023-04-20 06:59 UTC by YumNumm

単体テストを書いていてやりにくさを感じたので、アーキテクチャ周りを再度見直しました。

## 対応箇所
- `ViewModel`と各APIの間に`DataSource`と`UseCase`を追加しました
- Flutter 3.7.12にアップデートしました

## 概略図

![image](https://user-images.githubusercontent.com/73390859/233283513-5da01ff6-8c4f-4724-a062-874e9547bb20.png)

2023-04-20 07:02 UTC, YumNumm commented on ios/Runner.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = CPL7H8SHVM;
実機でデバッグを行うため、TeamIDを割り当てました。

![image](https://user-images.githubusercontent.com/73390859/233286601-088b7453-f236-4d58-bc12-6e86785f5f0b.png)

2023-04-20 09:57 UTC, blendthink requested changes
[must]
挙動変わってしまっているので、動作確認＆動画の添付、お願いします！

2023-04-20 09:57 UTC, blendthink commented on ios/Runner.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = CPL7H8SHVM;
[nits]
実案件では、基本的にメンバー全員が使用できるチームを設定するため、個人のチームを設定することはほぼありません。
どうしても個人のチームを利用したい場合は、レビューする側も問題なくアプリを実行できるように、 `--dart-define` などでそれぞれで設定した値を読み込み、設定するようにするのがより適切かなと思います。

2023-04-20 09:57 UTC, blendthink commented on .fvm/fvm_config.json
> +  "flutterSdkVersion": "3.7.12",
[感想]
ついでにバージョンあげた感じかなと思いますが、たまにパッチリリースでも不具合が発生することがあるため、今後で大丈夫ですが可能な限り Flutter やパッケージなどのバージョンアップ対応はプルリクエストを分けましょう 💪

2023-04-20 09:57 UTC, blendthink commented on lib/common/use_case/fake_use_case.dart
> +@visibleForTesting
[nits]
テストでのみ使用することを想定しているのであれば、 `test` ディレクトリに追加したほうが適切そうです。

2023-04-20 09:57 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +    ref.listen(weatherViewModelProvider, (_, next) {
[nits]
`select` を使って、 `failure` 以外の変更があっても通知が来ないようにしたほうが良さそうです。

2023-04-20 09:57 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +            );
[感想]
こうすると若干動作が変わりますが、こういう挙動もありですね〜 👍

2023-04-20 09:57 UTC, blendthink commented on lib/features/weather/viewmodel/weather_viewmodel.dart
[must]
`onReloadTap` あたりのコードの見直しお願いします！

2023-04-20 09:57 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +    ref.listen(weatherViewModelProvider, (_, next) {
[must]
同じ `Exception` が発生した場合、通知来なくなってしまっているような気がします。ご確認お願いします！

2023-04-20 10:30 UTC, YumNumm commented on ios/Runner.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = CPL7H8SHVM;
ありがとうございます
当該部分消去し修正しました。2b58bce9ae9b998342406a5495df0c2e6c890992

2023-04-20 10:46 UTC, YumNumm commented on lib/features/weather/screen/weather_screen.dart
> +    ref.listen(weatherViewModelProvider, (_, next) {
ありがとうございます
1つ目については、`Result`に`errorOrNull`関数を追加し対応しました。 cc173a0f43f9e55e714ee26cd763843400f0eb83
2つ目については、`AlertDialog`出した後、`pop`した時点で`WeatherVieWModel`のStateを初期値に戻すことで対応しました 97ccc590ebccd97225d83df40e0b8218c0ded711

2023-04-20 10:47 UTC, YumNumm commented on lib/features/weather/viewmodel/weather_viewmodel.dart
ありがとうございます!
修正漏れていました 
7887633f82b731fcbb639ccb605dec9290842fc1

2023-04-20 10:49 UTC, YumNumm commented on lib/common/use_case/fake_use_case.dart
> +@visibleForTesting
ありがとうございます！
ディレクトリ移動しました
0c361828a4cddd44798f21cdc6fa022a5ccba3a4

2023-04-20 11:00 UTC, YumNumm commented
@blendthink 
各種修正・挙動確認用の動画を会話の最初に添付しました
お手すきの際にご確認いただけたら幸いです。

2023-04-21 00:48 UTC, blendthink reviewed
@YumNumm 
いくつかコメントしましたのでご確認お願いします！

2023-04-21 00:48 UTC, blendthink commented on lib/common/model/result.dart
> +      );
[感想]
こういうものを用意しておくと便利でいいですね！

2023-04-21 00:48 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +      ref.read(weatherViewModelProvider.notifier).build();
[nits]
リセット用のメソッドが用意されているので、そちらを利用していた方が良さそうです。
`ref.refresh` もありますが、今回はそこまでの即時性は求めなくてもいい気がするので、 `ref.invalidate` で十分かなと思います。

https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/WidgetRef/invalidate.html

```suggestion
      ref.invalidate(weatherViewModelProvider);
```

2023-04-21 00:48 UTC, blendthink commented on lib/features/weather/viewmodel/weather_viewmodel.dart
> +    );
[nits]
若干ですが、このようにしたほうが可読性高まりそうです。

```suggestion
    state = useCase(req).when(
      success: (data) => Result.success(
        WeatherViewModelState(
          weatherCondition: data.weatherCondition,
          minTemperature: data.minTemperature,
          maxTemperature: data.maxTemperature,
        ),
      ),
      failure: Result.failure,
    );
```

2023-04-21 00:48 UTC, blendthink commented on test/common/use_case/fake_use_case.dart
> +@visibleForTesting
[nits]
`test` ディレクトリに移動したので、このアノテーションは不要そうです。

2023-04-24 00:55 UTC, YumNumm commented on lib/features/weather/screen/weather_screen.dart
> +      ref.read(weatherViewModelProvider.notifier).build();
ありがとうございました
変更しました
689ab99e5fe6a13f7fac9f2ab29ed2b58d7ba6c1

2023-04-24 00:57 UTC, YumNumm commented on lib/features/weather/viewmodel/weather_viewmodel.dart
> +    );
ありがとうございます
確かに、こちらのほうがきれいな書き方だと感じました。
修正しました 13d691c8a80a40515fca5fa592a41fe783e3b06a

2023-04-24 00:59 UTC, YumNumm commented on test/common/use_case/fake_use_case.dart
> +@visibleForTesting
ありがとうございます 修正しました ec12ea614abb4ef2f168a89b02a3e505615a5ede

2023-04-24 10:59 UTC, blendthink approved these changes
UseCase の実装とても参考になりました！
とても良い感じでテストコードが書けそうですね✨

![LGTM](https://image.lgtmoon.dev/167261)

2023-04-24 11:05 UTC, merged