Session 11: Thread Block
YumNumm/flutter-training pull request #41
Opened 2023-05-25 12:40 UTC by YumNumm

## 課題

close #24 

## 対応箇所

- [x] 使用する API を `fetchWeather()` から `syncFetchWeather()` に変更する
- [x] API の処理が戻るまで [CircularProgressIndicator] を表示する
---
- [x] APIの変更に合わせてUnit Test・Widget Testの修正

## 動作

| expected | actual(iPhone 14 Pro iOS 16.4) |
|----------| --------   |
| ![expected]     | ![actual] |

[expected]: https://github.com/yumemi-inc/flutter-training-template/blob/main/docs/sessions/images/thread_block/demo.gif?raw=true
[actual]: https://github.com/YumNumm/flutter-training/assets/73390859/5e6638c5-5ed0-497f-9fc4-5477f014340f

2023-05-25 13:03 UTC, YumNumm commented on test/features/weather/screen/weather_screen_test.dart
> +        findsWidgets,
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
こちらでももう少し確認しますが、なぜか`circularProgressIndicator`が2つ検出されてしまっているようです。
もし、原因がわかりそうでしたら教えていただけると助かります。

`CircularProgressIndicator`を呼び出している部分は以下で、実機では1度のみ呼び出されていることを確認済みです。
https://github.com/YumNumm/flutter-training/blob/9ed7e5aed728b436e622abf23f7603ec0a418ff3/lib/features/weather/screen/weather_screen.dart#L21

このテストは、`findsWidgets`にして仮で通しています。

<img width="1234" alt="image" src="https://github.com/YumNumm/flutter-training/assets/73390859/89a82027-a1f1-4f50-8694-16516076ac28">

2023-05-25 13:05 UTC, YumNumm commented on lib/common/extension/async_value_guard.dart
> +  Future<AsyncValue<T>> preservedGuard(
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
`AsyncValue.guard(Future<T>)`の拡張版として`preservedGuard`を作成しました。
成功時のみではなく、失敗時も直近のstateを維持するようにしています。

2023-05-25 13:06 UTC, YumNumm commented on lib/features/weather/model/weather_error_type.dart
> +class WeatherExcepiton implements Exception {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
`AsyncValue`を使うにあたり、`Exception`を使う必要があったので、
`WeatherErrorType`を定数として持つ`WeatherExcepiton`を定義しました

2023-05-25 13:08 UTC, YumNumm commented on lib/features/weather/screen/weather_screen.dart
> +      if ((previous?.isLoading ?? false) && !next.isLoading) {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
読み込み中 -> 読み込み中ではない の状態遷移のみ`context.pop`を呼び出すようにし、
`LoadingOverlay`を閉じてから、エラーを含むかどうかを判別し、
含む場合にエラーダイアログを出すようにしています。

2023-05-25 13:11 UTC, YumNumm commented on test/features/weather/screen/weather_screen_test.dart
> +    WidgetsBinding.instance.endOfFrame.then(
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
`routerProvider`では、初期ルートが`SplashRoute()`なため、表示された直後に`WeatherRoute()`へ遷移するようにしています。

2023-05-25 13:39 UTC, YumNumm commented on test/features/weather/screen/weather_screen_test.dart
> +    WidgetsBinding.instance.endOfFrame.then(
そもそも、`WeatherScreenTest`で`GoRouter`を利用する必要が無かったので、修正しました。
[fix: WeatherScreenTestでGoRouterを使わない形に変更](https://github.com/YumNumm/flutter-training/pull/41/commits/48c49396428331ed73d9dafc884fcb5ea5142b8e)

2023-05-25 13:43 UTC, YumNumm commented on lib/features/weather/data/weather_data_source.dart
> +    final weatherResponse = await Isolate.run(() async {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
デシリアライズもまとめて 別スレッドで実行しています
冒頭の映像からのVSCode「コールスタック」から 別スレッドで実行していることがわかります

2023-05-25 19:06 UTC, YumNumm commented on lib/features/weather/viewmodel/weather_viewmodel.dart
> +  AsyncValue<WeatherViewModelState?> build() => const AsyncData(null);
状態管理には、`AsyncValue`を使うようにしました

2023-05-31 03:22 UTC, blendthink requested changes
@YumNumm 
いったんいくつかコメントしましたのでご確認お願いします！

2023-05-31 03:22 UTC, blendthink commented on lib/features/weather/model/weather_error_type.dart
> +class WeatherExcepiton implements Exception {
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg) 
ファイル名を見ても、ここに天気についての例外クラスがあるのは若干違和感があり、別ファイルに切り出した方がすっきりしそうです。

2023-05-31 03:22 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +        showLoadingOverlay(context: context);
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
これ以降処理を行わないはずなので、 `return` しちゃったほうが、可読性向上できそうです。
```suggestion
        showLoadingOverlay(context: context);
        return;
```

2023-05-31 03:22 UTC, blendthink commented on lib/common/extension/async_value_guard.dart
> +  Future<AsyncValue<T>> preservedGuard(
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
今回の要件は初期値が null で AsyncNotifier で実装することが困難（初期値がローディングになってしまう）のため、独自に以前の値を保持するようにしなければ厳密な判定が難しかったと思います。このような便利な拡張関数を用意されていてステキです✨

2023-05-31 03:22 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +      if ((previous?.isLoading ?? false) && !next.isLoading) {
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg) 
個人的には↓のようにしたほうが見やすくなる気がしました。
```suggestion
      if (previous == null) {
        return;
      }
      
      // Call終了時にローディングを閉じる
      if (previous.isLoading && !next.isLoading) {
```

2023-05-31 03:22 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +          final errorType = (next.asError!.error as WeatherExcepiton).type;
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
ここで強制的に `WeatherExcepiton` にキャストしてしまっていますが、後々の UseCase や ViewModel で別の例外が発生するように変更されたときに気づきづらく、調査に時間がかかってしまいそうです。

![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
そのため、 強制キャストしないようにして、かつ、 `WeatherExcepiton` でないときもエラーダイアログを表示するようにするのはいかがでしょうか？

2023-05-31 09:31 UTC, YumNumm commented on lib/features/weather/screen/weather_screen.dart
> +        showLoadingOverlay(context: context);
ありがとうございます
修正しました
c86fc3d45b37de3e8f05a1342d9532e1465cf800

2023-05-31 09:46 UTC, YumNumm commented on lib/features/weather/screen/weather_screen.dart
> +          final errorType = (next.asError!.error as WeatherExcepiton).type;
確かにその方が良い実装そうです
修正しました。
0de0f2978a03ef231f01c7e9115aaa4f895239c7

---

![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
上記コミットのdiff部分、パターンマッチングを用いたらきれいに実装できそうですね
```dart
if (next.error is WeatherExcepiton) {
  final errorType = (next.error! as WeatherExcepiton).type;
  showErrorDialog(
    context: context,
    title: 'エラーが発生しました',
    message: errorType.message,
  );
  return;
}
showErrorDialog(
  context: context,
  title: 'エラーが発生しました',
  message: '不明なエラーが発生しました。\n'
      '${next.error}',
);
```

2023-05-31 09:50 UTC, YumNumm commented
@blendthink レビューありがとうございました。
ご指摘頂いた点修正しましたので お手すきの際に確認いただければと思います。
よろしくお願いします。

---

[WeatherExceptionファイル切り出しの件](https://github.com/YumNumm/flutter-training/pull/41#discussion_r1209962110)も対応済みです。
(なぜかコメントに対して リプライができませんでしたので こちらで報告させていただきます)
f9b7e0fdababaf1deb8017d182ea11146c505466

2023-05-31 09:54 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +          final errorType = (next.asError!.error as WeatherExcepiton).type;
@YumNumm 
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`next.error` が複数箇所で使われてしまっているため、ローカル変数に切り出して使いまわした方が見通し良くなり、可読性的にも保守性的にも良くなりそうです。

2023-05-31 10:07 UTC, YumNumm commented on lib/features/weather/screen/weather_screen.dart
> +          final errorType = (next.asError!.error as WeatherExcepiton).type;
@blendthink 
ありがとうございます! 
`next.error`の利用箇所が減ったうえ、`!`の利用回数も減らすことができました
ae62aff7f0511304f06a18cea61f98f55e9189be

2023-05-31 10:53 UTC, blendthink commented on lib/features/weather/screen/weather_screen.dart
> +          final errorType = (next.asError!.error as WeatherExcepiton).type;
@YumNumm 
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
このようにするともっとスッキリできそうです！
```dart
        final nextError = next.error;
        if (nextError != null) {
          if (nextError is WeatherExcepiton) {
            final errorType = nextError.type;
            showErrorDialog(
              context: context,
              title: 'エラーが発生しました',
              message: errorType.message,
            );
            return;
          }
          showErrorDialog(
            context: context,
            title: 'エラーが発生しました',
            message: '不明なエラーが発生しました。\n'
                '$nextError',
          );
          return;
        }
```

2023-05-31 10:57 UTC, YumNumm commented on lib/features/weather/screen/weather_screen.dart
> +          final errorType = (next.asError!.error as WeatherExcepiton).type;
@blendthink ありがとうございます!
修正しました!
8992bc4e69478cdc204e7441c0368e6009152da6

2023-06-02 06:15 UTC, YumNumm commented on lib/features/weather/screen/weather_screen.dart
> +      if ((previous?.isLoading ?? false) && !next.isLoading) {
ありがとうございます こちらの返信、失念しておりました
こちらで修正済みです
b73472b18c41756c7e2b8534eb45ed2479f20bf4

2023-06-05 09:44 UTC, blendthink approved these changes
ご対応ありがとうございます！！
そして、研修課題修了おめでとうございます 🎉 

![LGTM](https://image.lgtmoon.dev/140550)

2023-06-05 09:46 UTC, merged

2023-06-05 09:46 UTC, YumNumm commented
ありがとうございます!
こちらのレポジトリはArchiveして良いでしょうか?

2023-06-05 09:48 UTC, blendthink commented
好きなようにしていただいて大丈夫です 🙆‍♂️ 

、、ですが、後々見返したり、次の新卒の方が参画したときにレビューしていただくかもしれないので、削除はせずに残しておくことをおすすめします！（元からそのつもりかもですが念の為 🙇 ）